dist: trusty
language: python
install:
  - pip install --only-binary=numpy,scipy numpy nose scipy sklearn
  - pip install tensorflow
  - pip install git+https://github.com/hycis/TensorGraph.git@master

script:
  - echo "TensorGraph"
  - pytest test
